// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/go-sdk/lib/metrics (interfaces: Recorder)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/metrics/mock_metrics.go -package=mockmetrics github.com/biairmal/go-sdk/lib/metrics Recorder
//

// Package mockmetrics is a generated GoMock package.
package mockmetrics

import (
	reflect "reflect"

	metrics "github.com/biairmal/go-sdk/lib/metrics"
	gomock "go.uber.org/mock/gomock"
)

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// CounterInc mocks base method.
func (m *MockRecorder) CounterInc(name string, labels metrics.Labels) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CounterInc", name, labels)
}

// CounterInc indicates an expected call of CounterInc.
func (mr *MockRecorderMockRecorder) CounterInc(name, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CounterInc", reflect.TypeOf((*MockRecorder)(nil).CounterInc), name, labels)
}

// GaugeAdd mocks base method.
func (m *MockRecorder) GaugeAdd(name string, delta float64, labels metrics.Labels) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GaugeAdd", name, delta, labels)
}

// GaugeAdd indicates an expected call of GaugeAdd.
func (mr *MockRecorderMockRecorder) GaugeAdd(name, delta, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GaugeAdd", reflect.TypeOf((*MockRecorder)(nil).GaugeAdd), name, delta, labels)
}

// HistogramObserve mocks base method.
func (m *MockRecorder) HistogramObserve(name string, value float64, labels metrics.Labels) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HistogramObserve", name, value, labels)
}

// HistogramObserve indicates an expected call of HistogramObserve.
func (mr *MockRecorderMockRecorder) HistogramObserve(name, value, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HistogramObserve", reflect.TypeOf((*MockRecorder)(nil).HistogramObserve), name, value, labels)
}
