// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/go-sdk/lib/circuitbreaker (interfaces: Breaker)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/circuitbreaker/mock_circuitbreaker.go -package=mockcircuitbreaker github.com/biairmal/go-sdk/lib/circuitbreaker Breaker
//

// Package mockcircuitbreaker is a generated GoMock package.
package mockcircuitbreaker

import (
	context "context"
	reflect "reflect"

	circuitbreaker "github.com/biairmal/go-sdk/lib/circuitbreaker"
	gomock "go.uber.org/mock/gomock"
)

// MockBreaker is a mock of Breaker interface.
type MockBreaker struct {
	ctrl     *gomock.Controller
	recorder *MockBreakerMockRecorder
	isgomock struct{}
}

// MockBreakerMockRecorder is the mock recorder for MockBreaker.
type MockBreakerMockRecorder struct {
	mock *MockBreaker
}

// NewMockBreaker creates a new mock instance.
func NewMockBreaker(ctrl *gomock.Controller) *MockBreaker {
	mock := &MockBreaker{ctrl: ctrl}
	mock.recorder = &MockBreakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBreaker) EXPECT() *MockBreakerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockBreaker) Execute(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockBreakerMockRecorder) Execute(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockBreaker)(nil).Execute), ctx, fn)
}

// State mocks base method.
func (m *MockBreaker) State() circuitbreaker.State {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "State")
	ret0, _ := ret[0].(circuitbreaker.State)
	return ret0
}

// State indicates an expected call of State.
func (mr *MockBreakerMockRecorder) State() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "State", reflect.TypeOf((*MockBreaker)(nil).State))
}
