// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/go-sdk/lib/ratelimit (interfaces: Limiter)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/ratelimit/mock_ratelimit.go -package=mockratelimit github.com/biairmal/go-sdk/lib/ratelimit Limiter
//

// Package mockratelimit is a generated GoMock package.
package mockratelimit

import (
	context "context"
	reflect "reflect"

	ratelimit "github.com/biairmal/go-sdk/lib/ratelimit"
	gomock "go.uber.org/mock/gomock"
)

// MockLimiter is a mock of Limiter interface.
type MockLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockLimiterMockRecorder
	isgomock struct{}
}

// MockLimiterMockRecorder is the mock recorder for MockLimiter.
type MockLimiterMockRecorder struct {
	mock *MockLimiter
}

// NewMockLimiter creates a new mock instance.
func NewMockLimiter(ctrl *gomock.Controller) *MockLimiter {
	mock := &MockLimiter{ctrl: ctrl}
	mock.recorder = &MockLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimiter) EXPECT() *MockLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockLimiter) Allow(ctx context.Context, key string) (ratelimit.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, key)
	ret0, _ := ret[0].(ratelimit.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockLimiterMockRecorder) Allow(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockLimiter)(nil).Allow), ctx, key)
}
