# mocks.mk - Generate gomock mocks for SDK interfaces
#
# Provides: mocks, help-mocks. Prerequisite: include vars.mk first.
# Mocks are generated by the //go:generate directives next to each interface
# (logger.Logger, redis.Client/Pipeliner, repository.*, validator.Validator,
# tracer.Tracer, auth.Validator/Claims/Issuer, metrics.Recorder,
# ratelimit.Limiter, circuitbreaker.Breaker) into the nested module ./mocks,
# which has its own go.mod so go.uber.org/mock never becomes a dependency of
# the main module. Regenerate after changing any mocked interface.

include $(SCRIPTS_DIR)/vars.mk

# Packages that carry //go:generate mockgen directives.
MOCK_PKGS := ./logger/... ./redis/... ./repository/... ./validator/... ./tracer/... ./auth/... ./metrics/... ./ratelimit/... ./circuitbreaker/...

mocks: ## Regenerate interface mocks into the ./mocks module (go.uber.org/mock)
	$(ECHO_EMPTY)
	@echo "# Mocks"
	$(ECHO_EMPTY)
	@echo "$(INDENT)$(PREFIX_RUN)Generating mocks..."
	@go generate $(MOCK_PKGS)
	@echo "$(INDENT)$(PREFIX_RUN)Tidying mocks module..."
	@cd mocks && go mod tidy
	@echo "$(INDENT)$(PREFIX_OK)Mocks generated into ./mocks"
	$(ECHO_EMPTY)
	@echo "$(INDENT)$(PREFIX_OK)PROCESS COMPLETED SUCCESSFULLY"

help-mocks: ## Show mock targets and descriptions
	@echo "# Mocks"
	@echo "  make mocks ## Regenerate interface mocks into the ./mocks module"
