// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/go-sdk/lib/repository (interfaces: Repository,ReadRepository,WriteRepository,TransactionalRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/repository/mock_repository.go -package=mockrepository github.com/biairmal/go-sdk/lib/repository Repository,ReadRepository,WriteRepository,TransactionalRepository
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	repository "github.com/biairmal/go-sdk/lib/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository[TEntity any, TID comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder[TEntity, TID]
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder[TEntity any, TID comparable] struct {
	mock *MockRepository[TEntity, TID]
}

// NewMockRepository creates a new mock instance.
func NewMockRepository[TEntity any, TID comparable](ctrl *gomock.Controller) *MockRepository[TEntity, TID] {
	mock := &MockRepository[TEntity, TID]{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder[TEntity, TID]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository[TEntity, TID]) EXPECT() *MockRepositoryMockRecorder[TEntity, TID] {
	return m.recorder
}

// Count mocks base method.
func (m *MockRepository[TEntity, TID]) Count(ctx context.Context, filter repository.Filter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder[TEntity, TID]) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository[TEntity, TID])(nil).Count), ctx, filter)
}

// Create mocks base method.
func (m *MockRepository[TEntity, TID]) Create(ctx context.Context, entity *TEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder[TEntity, TID]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository[TEntity, TID])(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockRepository[TEntity, TID]) Delete(ctx context.Context, id TID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder[TEntity, TID]) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository[TEntity, TID])(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockRepository[TEntity, TID]) Exists(ctx context.Context, id TID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockRepositoryMockRecorder[TEntity, TID]) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockRepository[TEntity, TID])(nil).Exists), ctx, id)
}

// GetByID mocks base method.
func (m *MockRepository[TEntity, TID]) GetByID(ctx context.Context, id TID) (*TEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*TEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder[TEntity, TID]) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository[TEntity, TID])(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockRepository[TEntity, TID]) List(ctx context.Context, opts *repository.ListOptions) ([]*TEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*TEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder[TEntity, TID]) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository[TEntity, TID])(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockRepository[TEntity, TID]) Update(ctx context.Context, id TID, entity *TEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder[TEntity, TID]) Update(ctx, id, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository[TEntity, TID])(nil).Update), ctx, id, entity)
}

// MockReadRepository is a mock of ReadRepository interface.
type MockReadRepository[TEntity any, TID comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockReadRepositoryMockRecorder[TEntity, TID]
	isgomock struct{}
}

// MockReadRepositoryMockRecorder is the mock recorder for MockReadRepository.
type MockReadRepositoryMockRecorder[TEntity any, TID comparable] struct {
	mock *MockReadRepository[TEntity, TID]
}

// NewMockReadRepository creates a new mock instance.
func NewMockReadRepository[TEntity any, TID comparable](ctrl *gomock.Controller) *MockReadRepository[TEntity, TID] {
	mock := &MockReadRepository[TEntity, TID]{ctrl: ctrl}
	mock.recorder = &MockReadRepositoryMockRecorder[TEntity, TID]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadRepository[TEntity, TID]) EXPECT() *MockReadRepositoryMockRecorder[TEntity, TID] {
	return m.recorder
}

// Count mocks base method.
func (m *MockReadRepository[TEntity, TID]) Count(ctx context.Context, filter repository.Filter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockReadRepositoryMockRecorder[TEntity, TID]) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockReadRepository[TEntity, TID])(nil).Count), ctx, filter)
}

// Exists mocks base method.
func (m *MockReadRepository[TEntity, TID]) Exists(ctx context.Context, id TID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockReadRepositoryMockRecorder[TEntity, TID]) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockReadRepository[TEntity, TID])(nil).Exists), ctx, id)
}

// GetByID mocks base method.
func (m *MockReadRepository[TEntity, TID]) GetByID(ctx context.Context, id TID) (*TEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*TEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReadRepositoryMockRecorder[TEntity, TID]) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReadRepository[TEntity, TID])(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockReadRepository[TEntity, TID]) List(ctx context.Context, opts *repository.ListOptions) ([]*TEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*TEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockReadRepositoryMockRecorder[TEntity, TID]) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReadRepository[TEntity, TID])(nil).List), ctx, opts)
}

// MockWriteRepository is a mock of WriteRepository interface.
type MockWriteRepository[TEntity any, TID comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockWriteRepositoryMockRecorder[TEntity, TID]
	isgomock struct{}
}

// MockWriteRepositoryMockRecorder is the mock recorder for MockWriteRepository.
type MockWriteRepositoryMockRecorder[TEntity any, TID comparable] struct {
	mock *MockWriteRepository[TEntity, TID]
}

// NewMockWriteRepository creates a new mock instance.
func NewMockWriteRepository[TEntity any, TID comparable](ctrl *gomock.Controller) *MockWriteRepository[TEntity, TID] {
	mock := &MockWriteRepository[TEntity, TID]{ctrl: ctrl}
	mock.recorder = &MockWriteRepositoryMockRecorder[TEntity, TID]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriteRepository[TEntity, TID]) EXPECT() *MockWriteRepositoryMockRecorder[TEntity, TID] {
	return m.recorder
}

// Create mocks base method.
func (m *MockWriteRepository[TEntity, TID]) Create(ctx context.Context, entity *TEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWriteRepositoryMockRecorder[TEntity, TID]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWriteRepository[TEntity, TID])(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockWriteRepository[TEntity, TID]) Delete(ctx context.Context, id TID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWriteRepositoryMockRecorder[TEntity, TID]) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWriteRepository[TEntity, TID])(nil).Delete), ctx, id)
}

// Update mocks base method.
func (m *MockWriteRepository[TEntity, TID]) Update(ctx context.Context, id TID, entity *TEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWriteRepositoryMockRecorder[TEntity, TID]) Update(ctx, id, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWriteRepository[TEntity, TID])(nil).Update), ctx, id, entity)
}

// MockTransactionalRepository is a mock of TransactionalRepository interface.
type MockTransactionalRepository[TEntity any, TID comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionalRepositoryMockRecorder[TEntity, TID]
	isgomock struct{}
}

// MockTransactionalRepositoryMockRecorder is the mock recorder for MockTransactionalRepository.
type MockTransactionalRepositoryMockRecorder[TEntity any, TID comparable] struct {
	mock *MockTransactionalRepository[TEntity, TID]
}

// NewMockTransactionalRepository creates a new mock instance.
func NewMockTransactionalRepository[TEntity any, TID comparable](ctrl *gomock.Controller) *MockTransactionalRepository[TEntity, TID] {
	mock := &MockTransactionalRepository[TEntity, TID]{ctrl: ctrl}
	mock.recorder = &MockTransactionalRepositoryMockRecorder[TEntity, TID]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionalRepository[TEntity, TID]) EXPECT() *MockTransactionalRepositoryMockRecorder[TEntity, TID] {
	return m.recorder
}

// Count mocks base method.
func (m *MockTransactionalRepository[TEntity, TID]) Count(ctx context.Context, filter repository.Filter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTransactionalRepositoryMockRecorder[TEntity, TID]) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTransactionalRepository[TEntity, TID])(nil).Count), ctx, filter)
}

// Create mocks base method.
func (m *MockTransactionalRepository[TEntity, TID]) Create(ctx context.Context, entity *TEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransactionalRepositoryMockRecorder[TEntity, TID]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionalRepository[TEntity, TID])(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockTransactionalRepository[TEntity, TID]) Delete(ctx context.Context, id TID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTransactionalRepositoryMockRecorder[TEntity, TID]) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTransactionalRepository[TEntity, TID])(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockTransactionalRepository[TEntity, TID]) Exists(ctx context.Context, id TID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockTransactionalRepositoryMockRecorder[TEntity, TID]) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockTransactionalRepository[TEntity, TID])(nil).Exists), ctx, id)
}

// GetByID mocks base method.
func (m *MockTransactionalRepository[TEntity, TID]) GetByID(ctx context.Context, id TID) (*TEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*TEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTransactionalRepositoryMockRecorder[TEntity, TID]) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTransactionalRepository[TEntity, TID])(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTransactionalRepository[TEntity, TID]) List(ctx context.Context, opts *repository.ListOptions) ([]*TEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*TEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTransactionalRepositoryMockRecorder[TEntity, TID]) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTransactionalRepository[TEntity, TID])(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockTransactionalRepository[TEntity, TID]) Update(ctx context.Context, id TID, entity *TEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTransactionalRepositoryMockRecorder[TEntity, TID]) Update(ctx, id, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTransactionalRepository[TEntity, TID])(nil).Update), ctx, id, entity)
}

// WithTx mocks base method.
func (m *MockTransactionalRepository[TEntity, TID]) WithTx(tx *sql.Tx) repository.Repository[TEntity, TID] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.Repository[TEntity, TID])
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTransactionalRepositoryMockRecorder[TEntity, TID]) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTransactionalRepository[TEntity, TID])(nil).WithTx), tx)
}
