// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/go-sdk/validator (interfaces: Validator)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/validator/mock_validator.go -package=mockvalidator github.com/biairmal/go-sdk/validator Validator
//

// Package mockvalidator is a generated GoMock package.
package mockvalidator

import (
	reflect "reflect"

	validator "github.com/biairmal/go-sdk/validator"
	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockValidator) Register(tag string, fn func(validator.FieldLevel) bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", tag, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockValidatorMockRecorder) Register(tag, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockValidator)(nil).Register), tag, fn)
}

// ValidateStruct mocks base method.
func (m *MockValidator) ValidateStruct(s any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStruct", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateStruct indicates an expected call of ValidateStruct.
func (mr *MockValidatorMockRecorder) ValidateStruct(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStruct", reflect.TypeOf((*MockValidator)(nil).ValidateStruct), s)
}

// ValidateVar mocks base method.
func (m *MockValidator) ValidateVar(field any, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateVar", field, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateVar indicates an expected call of ValidateVar.
func (mr *MockValidatorMockRecorder) ValidateVar(field, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateVar", reflect.TypeOf((*MockValidator)(nil).ValidateVar), field, tag)
}
