// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/go-sdk/lib/logger (interfaces: Logger)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/logger/mock_logger.go -package=mocklogger github.com/biairmal/go-sdk/lib/logger Logger
//

// Package mocklogger is a generated GoMock package.
package mocklogger

import (
	context "context"
	reflect "reflect"

	logger "github.com/biairmal/go-sdk/lib/logger"
	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), varargs...)
}

// DebugWithContext mocks base method.
func (m *MockLogger) DebugWithContext(ctx context.Context, msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "DebugWithContext", varargs...)
}

// DebugWithContext indicates an expected call of DebugWithContext.
func (mr *MockLoggerMockRecorder) DebugWithContext(ctx, msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugWithContext", reflect.TypeOf((*MockLogger)(nil).DebugWithContext), varargs...)
}

// Debugf mocks base method.
func (m *MockLogger) Debugf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerMockRecorder) Debugf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLogger)(nil).Debugf), varargs...)
}

// DebugfWithContext mocks base method.
func (m *MockLogger) DebugfWithContext(ctx context.Context, format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "DebugfWithContext", varargs...)
}

// DebugfWithContext indicates an expected call of DebugfWithContext.
func (mr *MockLoggerMockRecorder) DebugfWithContext(ctx, format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugfWithContext", reflect.TypeOf((*MockLogger)(nil).DebugfWithContext), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// ErrorWithContext mocks base method.
func (m *MockLogger) ErrorWithContext(ctx context.Context, msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorWithContext", varargs...)
}

// ErrorWithContext indicates an expected call of ErrorWithContext.
func (mr *MockLoggerMockRecorder) ErrorWithContext(ctx, msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorWithContext", reflect.TypeOf((*MockLogger)(nil).ErrorWithContext), varargs...)
}

// Errorf mocks base method.
func (m *MockLogger) Errorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerMockRecorder) Errorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLogger)(nil).Errorf), varargs...)
}

// ErrorfWithContext mocks base method.
func (m *MockLogger) ErrorfWithContext(ctx context.Context, format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorfWithContext", varargs...)
}

// ErrorfWithContext indicates an expected call of ErrorfWithContext.
func (mr *MockLoggerMockRecorder) ErrorfWithContext(ctx, format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorfWithContext", reflect.TypeOf((*MockLogger)(nil).ErrorfWithContext), varargs...)
}

// Fatal mocks base method.
func (m *MockLogger) Fatal(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatal", varargs...)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockLoggerMockRecorder) Fatal(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLogger)(nil).Fatal), varargs...)
}

// FatalWithContext mocks base method.
func (m *MockLogger) FatalWithContext(ctx context.Context, msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FatalWithContext", varargs...)
}

// FatalWithContext indicates an expected call of FatalWithContext.
func (mr *MockLoggerMockRecorder) FatalWithContext(ctx, msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FatalWithContext", reflect.TypeOf((*MockLogger)(nil).FatalWithContext), varargs...)
}

// Fatalf mocks base method.
func (m *MockLogger) Fatalf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockLoggerMockRecorder) Fatalf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockLogger)(nil).Fatalf), varargs...)
}

// FatalfWithContext mocks base method.
func (m *MockLogger) FatalfWithContext(ctx context.Context, format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FatalfWithContext", varargs...)
}

// FatalfWithContext indicates an expected call of FatalfWithContext.
func (mr *MockLoggerMockRecorder) FatalfWithContext(ctx, format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FatalfWithContext", reflect.TypeOf((*MockLogger)(nil).FatalfWithContext), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// InfoWithContext mocks base method.
func (m *MockLogger) InfoWithContext(ctx context.Context, msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoWithContext", varargs...)
}

// InfoWithContext indicates an expected call of InfoWithContext.
func (mr *MockLoggerMockRecorder) InfoWithContext(ctx, msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoWithContext", reflect.TypeOf((*MockLogger)(nil).InfoWithContext), varargs...)
}

// Infof mocks base method.
func (m *MockLogger) Infof(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerMockRecorder) Infof(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLogger)(nil).Infof), varargs...)
}

// InfofWithContext mocks base method.
func (m *MockLogger) InfofWithContext(ctx context.Context, format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfofWithContext", varargs...)
}

// InfofWithContext indicates an expected call of InfofWithContext.
func (mr *MockLoggerMockRecorder) InfofWithContext(ctx, format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfofWithContext", reflect.TypeOf((*MockLogger)(nil).InfofWithContext), varargs...)
}

// Panic mocks base method.
func (m *MockLogger) Panic(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Panic", varargs...)
}

// Panic indicates an expected call of Panic.
func (mr *MockLoggerMockRecorder) Panic(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panic", reflect.TypeOf((*MockLogger)(nil).Panic), varargs...)
}

// PanicWithContext mocks base method.
func (m *MockLogger) PanicWithContext(ctx context.Context, msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PanicWithContext", varargs...)
}

// PanicWithContext indicates an expected call of PanicWithContext.
func (mr *MockLoggerMockRecorder) PanicWithContext(ctx, msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PanicWithContext", reflect.TypeOf((*MockLogger)(nil).PanicWithContext), varargs...)
}

// Panicf mocks base method.
func (m *MockLogger) Panicf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Panicf", varargs...)
}

// Panicf indicates an expected call of Panicf.
func (mr *MockLoggerMockRecorder) Panicf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panicf", reflect.TypeOf((*MockLogger)(nil).Panicf), varargs...)
}

// PanicfWithContext mocks base method.
func (m *MockLogger) PanicfWithContext(ctx context.Context, format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PanicfWithContext", varargs...)
}

// PanicfWithContext indicates an expected call of PanicfWithContext.
func (mr *MockLoggerMockRecorder) PanicfWithContext(ctx, format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PanicfWithContext", reflect.TypeOf((*MockLogger)(nil).PanicfWithContext), varargs...)
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), varargs...)
}

// WarnWithContext mocks base method.
func (m *MockLogger) WarnWithContext(ctx context.Context, msg string, fields ...logger.Field) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnWithContext", varargs...)
}

// WarnWithContext indicates an expected call of WarnWithContext.
func (mr *MockLoggerMockRecorder) WarnWithContext(ctx, msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnWithContext", reflect.TypeOf((*MockLogger)(nil).WarnWithContext), varargs...)
}

// Warnf mocks base method.
func (m *MockLogger) Warnf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerMockRecorder) Warnf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLogger)(nil).Warnf), varargs...)
}

// WarnfWithContext mocks base method.
func (m *MockLogger) WarnfWithContext(ctx context.Context, format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnfWithContext", varargs...)
}

// WarnfWithContext indicates an expected call of WarnfWithContext.
func (mr *MockLoggerMockRecorder) WarnfWithContext(ctx, format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnfWithContext", reflect.TypeOf((*MockLogger)(nil).WarnfWithContext), varargs...)
}
